### ISSUE TITLE
get_dispatched_platforms issue

### ISSUE THREAD

**Issue by carueda** [mbari-org/odss2dash#6]
When client makes request http://tethysdash2.shore.mbari.org:3033/api/runtime/platforms

```
INFO  odss2dash::server::dispatched] get_dispatched_platforms
thread 'tokio-runtime-worker' panicked at src/server/dispatched.rs:58:28:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by carueda** [comment]
A restart of the odss2dash container seemed to resolve the issue, from both the point of view of dash4, where I first noted the issue, and per the log:

```
Platform cache initialized with 308 platforms found in TrackingDB/ODSS
Loading './dispatched.json'
api : https://okeanids.mbari.org/odss2dash/api
doc : https://okeanids.mbari.org/odss2dash/apidoc/
spec: https://okeanids.mbari.org/odss2dash/api-docs/openapi.json
Server listening on 0.0.0.0:3033

Dispatcher is running  (polling every 60 secs)

Dispatching any new positions for 153 platforms
    Paragon (54065b5560d0e168c88d4016): new positions ....................
    wgTiny (54065b5560d0e168c88d403e): new positions ....................
    makai (54065b5560d0e168c88d4043): new positions ....................
    DAllanB (54065b5560d0e168c88d4045): new positions ....................
    dorado (54065b5560d0e168c88d4055): new positions ....................
    m1 (54065b5560d0e168c88d405e): new positions ....................
    oa2 (54065b5560d0e168c88d4065): new positions ....................
    R_CARSON (54065b5560d0e168c88d4085): new positions ....................
    daphne (54065b5560d0e168c88d4086): new positions ....................
    NPS_G34 (54065b5560d0e168c88d4087): new positions ....................

[2024-10-30T05:07:39Z ERROR odss2dash::trackdb_client] GET /tracks params={"platformID": "542c2d565afd283527d11258", "returnSRS": "4326", "lastNumberOfFixes": "20", "returnFormat": "json"}: error: Io Error: timed out
    338186132 (5554feda0f1d1644883796a7): new positions ....................
    ahi (57645c3c5c8870392f761d9a): new positions ....................
    369970573 (58e5b7cb8d4d8c07e7645df0): new positions ....................
    mapper2 (595b972a9cc530a40c4f6f07): new positions ....................
    paragon (5978bb0d7e0e448124ea749f): new positions ....................
    galene (5c1ab75f79309c4bb75e7099): new positions ....................

[2024-10-30T05:08:01Z INFO  odss2dash::server::dispatched] get_dispatched_platforms
[2024-10-30T05:08:02Z ERROR odss2dash::trackdb_client] GET /tracks params={"platformID": "5d4ca848236af7bc5def985b", "returnFormat": "json", "returnSRS": "4326", "lastNumberOfFixes": "20"}: error: Io Error: timed out
    pontus (5d5b2ea653a65f9ec656d872): new positions ....................
    brizo (5de994b4750d3b77feb29034): new positions ....................
    CPFBOG3 (5f16122fd02e3d4b2eada6b1): new positions ....
    BRBOGRVR (613939af24bc889c8ebd5d1e): new positions ....................
    WEC (61398b4024bc88eec0bd5d22): new positions ....................
    Docking-Buoy (624c9eb63d9fd580f886587c): new positions ....................
    WW_214007 (6446b4d298082f45ab087bd5): new positions ....................
    ecohab23-2 (651760a52108ad186f750780): new positions .....
```

but then:
```
thread '<unnamed>' panicked at src/dispatcher.rs:205:41:
called `Result::unwrap()` on an `Err` value: Os { code: 13, 
  kind: PermissionDenied, message: "Permission denied" }
```

**Comment by carueda** [comment]
Yes, it was a permission issue.  The fix, in the compose file, is to set the service user to align with the host user, in our case:
```yaml
user: '11035:20'
```
(but interesting that the issue was not manifested before)
